### ISSUE TITLE
Mosaic addons dependencies

### ISSUE THREAD

**Issue by d3cod3** [Daandelange/ofxAddonTool#1]
I've just updated two addons source dependency, rolling back to the original one:

https://github.com/Akira-Hayasaka/ofxGLEditor
https://github.com/danomatika/ofxMidi

please update the addons.txt when you can.

**Comment by Daandelange** [comment]
Sure, I'll look at this tomorrow. :)
By the way, these settings should be in Mosaic's config, so probably move `addons.txt` one level down. (The included one should only be the first example.)

Thomas also suggested merging with [ofPackageManager](https://github.com/thomasgeissl/ofPackageManager), which seems a bit (too?) feature-full, or making it somehow compatible with ofxAddonTool, thinking about it...

**Comment by Daandelange** [comment]
I just fixed this properly. You can update ofxAddonTool in mosaic, it will now use `Mosaic/addons.txt` now (move it there).

**Comment by d3cod3** [comment]
Ok, just pushed the commit, ofxAddonsTool updated and copied addons.txt in Mosaic/addons.txt !

**Comment by d3cod3** [comment]
I just edited the addons.txt in Mosaic, but just so you know, the ofxPython branch is master now

**Comment by Daandelange** [comment]
thanks :)
